name: Sync Docker Image To Aliyun
# 手动触发
on:
  workflow_dispatch:

jobs:
  sync_image:
    runs-on: ubuntu-latest
    steps:
      # 拉取代码（必需）
      - name: Checkout code
        uses: actions/checkout@v4

      # 安装 skopeo
      - name: Install skopeo
        run: sudo apt update && sudo apt install -y skopeo

      # 执行镜像同步（明文密码版）
      - name: Sync image
        env:
          # 阿里云镜像仓库地址
          ALI_REG: crpi-hhnhkp03op15g3f8.cn-hangzhou.personal.cr.aliyuncs.com
          # 阿里云ACR用户名
          ALI_USER: 乌龙网客
        run: |
          skopeo copy \
            docker://docker.io/tmoonlight/nspclient:latest \
            docker://${ALI_REG}/zwnlove/nspclient:latest \
            --dest-creds ${ALI_USER}:123369Zw
